language: android
android:
  components:
  - android-26
  - build-tools-27.0.3
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script:
- "./gradlew assembleDebug"
notifications:
  slack:
    secure: E+pI7DLGpyqWwWn/ViQ+9YWmt+CSnCjGFwhJFF7cIp2tAdfasa23w4tDYkjsUD38oWyqrWOf4ZF3QojzDZgN82OpEHoBp7xcPD5UsUH1Qs1sYkWc1ePdmST/VpypBmdLqLj2lciMt9iaZ116mRqMtxWw6UfSx8m2une9/tKYoNLf4VmK3E97nMGkVnx5kk/XhkP8w66IWqQ8A/rtd1VbYfepYt26MX7s3pkesdQm3SdnQM/8XsS5EPrEZsaq3hKgODuGIJ4ypothNqPhXyN09A7b0j/IGoEfmktZqRVEYsY8XeodBoABYzH/TL0MTxM/IWQldjL+4eGfr1fCO/nPDMW6zo4Lj8Y3Wj3E3QSBslo/y+xeC+/XJPO+AipsUSMBcmOwfuEIs36nPwmS+kTQmzRKMdgDUlvDD9dmtsDYEskDDGK7pWN0Gg4Q+jThzLA7bO+bjNfbJa2vPYIuNMlUdNva0deQXZENJtSK9b4C6TnRfP8tNR4JKsx4xQnTjCR6zjpVbTBGDKJfquePImXzSArhHZo747BW/mYcXIpAql9/kj52pZNqnMgYau+FlDcfytlnCf9SPGMfvBt43jR0twfoAnRGoN8fZPjkQ5hXhfY5oGRN2Qzy4SFFlGBWN3yJF9ZhtVeaUeOBfmddsxMrddFn40smiCScnrMa6psvyrY=
