language: android
android:
  components:
    - android-26
    - build-tools-27.0.3
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
- ./gradlew assembleDebug

notifications:
  slack:
    secure: Sp1ZxbPdp51rECamgDJi9h6V7xHUfV0N0Bj+v9qG4DQD2b6PbfMHLIXKPf7zXMKVTWnPVEzAu270vMSl+ICdwUaSwy1Jd50Fu66pHvd8GTpCpECgEtnnTM1hhkotS4tee7hjHmo9CfE7fbZqRjsx1aGEn9XIo4nKGzetA8/7Oj0SasEXDIxOFXNxWN23BdNf03oC0k878XGJ/ThhOXCPkzzcuxk65PQWSMPU+wNNKH7AVe8IyXQY0IG71rVa+rTYYCRMQFCtBRQktWSZJ7se7i78BKtey2+THeCwX7KYZZz6GfKAlRJtjits5ssrInIDJGOSOUjp4VK8cf4PPNtE0VIA9d64dZAkbHzJUXfGggfvR8+TonNCgpuP32bKCEOlrzit3kPAUPOlkyphOCB5BG6kt7xCmK1eMdEuSXYcI9TpwKYktJyg/aSySa10gKivteaVyZdplxHd0tscBTiKid05Y4fiYGD61gczUFwpH9AticLj3AOpVG1WLXq/a5