# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #  gradle(task: "clean assembleRelease")
  #  crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  desc "Create screenshots"
  lane :screenshots do
    sh("adb shell am broadcast -a com.android.systemui.demo -e command enter")
    # sh("adb shell am broadcast -a com.android.systemui.demo -e command clock -e hhmm 1234")
    sh("adb shell am broadcast -a com.android.systemui.demo -e command battery -e plugged false")
    sh("adb shell am broadcast -a com.android.systemui.demo -e command battery -e level 100")
    sh("adb shell am broadcast -a com.android.systemui.demo -e command network -e wifi show -e level 4")
    sh("adb shell am broadcast -a com.android.systemui.demo -e command network -e mobile show -e datatype none -e level 4")
    sh("adb shell am broadcast -a com.android.systemui.demo -e command notifications -e visible false")
    capture_android_screenshots
    sh("adb shell am broadcast -a com.android.systemui.demo -e command exit")
    # upload_to_play_store
  end
end
